intave-id:

#Global cheat-value to not allow the player to join.
#10 = 10% ; 9 = 90% ; Only whole numbers
value: 10

#Kick message to the player. Use \n to start a new line.
#Placeholders: {player} [uuid} {value}
deny-message: "§cIntave \n\n §"


execute-command: false
#Same placeholders as above
command: "/ban {player} You have reached the cheat-value limit"